---
title: "Classification"
author: "Alfa Pradana"
---

## Import library

```{python}
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import mutual_info_score
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression
```

## Data preparation

We will use the lead scoring Bank Marketing dataset https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv

```{python}
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv")
df.head()
```

### Missing values checking

```{python}
df.dtypes
```

```{python}
df.isnull().sum()
```

There are 5 columns with missing values:
- `lead_source` as object
- `industry` as object
- `annual_income` as numeric
- `employment_status` as object
- `location` as object

For categorical features, I replace them with `NA`, and for numerical features I replace it with with `0.0`

```{python}
categorical = df.dtypes[df.dtypes == "object"].index.tolist()
categorical
```

```{python}
numerical = df.dtypes[df.dtypes != "object"].index.tolist()
numerical
```

```{python}
for col in categorical:
    df[col] = df[col].fillna("NA")

for col in numerical:
    df[col] = df[col].fillna(0.0)

df.isnull().sum()
```

### The most frequent category in `industry`

```{python}
df["industry"].value_counts()
```

`retail` is the most frequent category in `industry` with 203 occurrences.

### Correlation matrix for the numerical features

```{python}
corr_mtx = df[numerical].corr()
corr_mtx.style.background_gradient(cmap='coolwarm')
```

```{python}
df[['number_of_courses_viewed', 'annual_income', 'interaction_count']].corrwith(df.lead_score).abs()
```

```{python}
df[['number_of_courses_viewed', 'annual_income', 'lead_score']].corrwith(df.interaction_count).abs()
```

Based on the given correlation matrix above, the biggest correlation is `annual_income` with `interaction_count` with correlation of `0.027036`.

### Splitting the data

Perform the train/validation/test split with Scikit-Learn's `train_test_split()` function.

```{python}
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
len(df_full_train), len(df_test)
```

If we can get the 20% of the data for validation and 60% for training, we need to set the `test_size` parameter to 0.25 (because 0.25 * 0.8 = 0.2).

```{python}
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
len(df_train), len(df_val), len(df_test)
```

Make sure that the target value `converted` is not in the dataframe

```{python}
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train["converted"]
del df_val["converted"]
del df_test["converted"]
```

## Feature engineering

### The biggest of mutual information

Mutual information is the concept from information theory that measures the amount of information obtained about one random variable through another random variable. In the context of feature selection for machine learning, mutual information can be used to quantify the dependency between a feature and the target variable.

```{python}
def mutual_info_category_score(series):
    return mutual_info_score(series, y_train)

mi = df_train[categorical].apply(mutual_info_category_score)
mi.sort_values(ascending=False).round(2)
```

The biggest mutual information is `lead_source` with `0.04`.

```{python}
len(df_train), len(df_val), len(df_test)
```

### One-hot encoding

```{python}
df_train[categorical].nunique()
```

```{python}
numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']
train_dicts = df_train[categorical +  numerical].to_dict(orient='records')
train_dicts[0]
```

```{python}
dv = DictVectorizer(sparse=False)
dv.fit(train_dicts)
dv.get_feature_names_out()
```

```{python}
X_train = dv.transform(train_dicts)
X_train.shape
```

```{python}
val_dicts = df_val[categorical +  numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)
```

## Logistic Regression

```{python}
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)
```

Accuracy on the validation dataset

```{python}
y_pred = model.predict_proba(X_val)[:, 1]
conv_decision = (y_pred >= 0.5)
original_accuracy = (y_val == conv_decision).mean()
print(f"Original accuracy with all features: {original_accuracy:.2f}\n")
```

Original accuracy with all features: `0.70`

### Feature elimination based on the accuracy 

```{python}
features = categorical + numerical
for feature in features:
    selected_features = [f for f in features if f != feature]

    train_dicts = df_train[selected_features].to_dict(orient='records')
    X_train = dv.transform(train_dicts)

    val_dicts = df_val[selected_features].to_dict(orient='records')
    X_val = dv.transform(val_dicts)

    # train the model
    model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    # evaluate the model
    y_pred = model.predict_proba(X_val)[:, 1]
    conv_decision = (y_pred >= 0.5)
    accuracy = (y_val == conv_decision).mean()

    diff = np.abs(accuracy - original_accuracy)

    print(f"{accuracy:.5f} (difference: {diff:.5f}) accuracy with no '{feature}'")
```

The smallest difference is `industry`, it means that if we drop `industry` feature, the accuracy will be the same as the original accuracy with all features.

### Best regularization parameter

```{python}
params = [0.01, 0.1, 1, 10, 100]
for C in params:
    train_dicts = df_train[categorical + numerical].to_dict(orient='records')
    X_train = dv.transform(train_dicts)

    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    conv_decision = (y_pred >= 0.5)
    accuracy = (y_val == conv_decision).mean()

    print(f"{accuracy:.3f} for parameter C={C}")
```

The best tuning parameter `C` is `0.01`.

