project:
  type: website

website:
  title: "Machine Learning Zoomcamp"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: 02_linear_regression.qmd
        text: Linear Regression
      - href: 03_classification.qmd
        text: Logistic Regression
      - href: 04_evaluation.qmd
        text: Evaluation
      - href: 05_development.qmd
        text: Deployment
      - href: 06_trees.qmd
        text: Trees

format:
  html:
    embed-resources: true
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false