---
title: " "
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
```

## Membuat peubah baru
```{r}
data("iris")
iris <- iris %>% mutate(Petal=Petal.Length+Petal.Width)
head(iris)
iris <- iris %>% mutate(Sepal=Sepal.Length+Sepal.Width)
head(iris)
```

## Data munging

Subsetting baris dengan menggunakan fungsi filter

```{r}
datatable(iris %>% filter(Species=="versicolor") )
```


Subsetting baris dengan menggunakan fungsi select

```{r}
datatable(iris %>% select(Species,Sepal,Petal) )
```


##Data Sorting

```{r}
#scr ascending
datatable(iris %>% arrange(Sepal))
```

```{r}
#scr desc
datatable(iris %>% arrange(desc(Sepal.Length),desc(Sepal.Width)))
```

```{r}
#scr
datatable(iris<-iris %>% arrange(Petal,desc(Sepal)))
```


##Join data frame

```{r}
irisx<-data.frame(Jenis=c("setosa","versicolor","rose"),kode=c(1,2,3))
datatable(irisx)
```

###innerjoin

```{r}
x<-iris %>% inner_join(irisx,by=c("Species"="Jenis"))
datatable(x)
```

###leftjoin

```{r}
y<-iris %>% left_join(irisx,by=c("Species"="Jenis"))
datatable(y)
```

###right join

```{r}
y<-iris %>% right_join(irisx,by=c("Species"="Jenis"))
datatable(y)
```

###fulljoin

```{r}
y<-iris %>% full_join(irisx,by=c("Species"="Jenis"))
datatable(y)
```

##Agregat

###summarise

```{r}
iris1<-iris %>% summarise(n=n(), maks=max(Sepal), min=min(Sepal), rataan=mean(Sepal))
datatable(iris1)
```

```{r}
iris2<-iris %>% summarise(n=n(), maks=max(Petal), min=min(Petal), rataan=mean(Petal))
datatable(iris2)
```


###group by

```{r}
iris3<-iris %>% group_by(Species) %>% summarise(n=n(),rataan=mean(Sepal),s=sd(Sepal))
datatable(iris3)
```

```{r}
iris4<-iris %>% group_by(Species) %>% summarise(n=n(),rataan=mean(Petal),s=sd(Petal))
datatable(iris4)
```

